import type { Metadata } from "next";
import { LegalPage, H2, P, UL, LI } from "../legal/_components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy — Sage",
  description: "How Sage collects, uses, and protects your information.",
};

const SUPPORT_EMAIL = "support@answerswithsage.xyz";

export default function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" effectiveDate="May 23, 2026">
      <P>
        Sage (&ldquo;Sage,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) is a
        Socratic AI companion that helps you think through questions in
        conversation. This Privacy Policy explains what information we collect,
        why, who we share it with, and the choices and rights you have. We
        wrote it in plain language on purpose.
      </P>
      <P>
        <strong>You are talking to an AI.</strong> Sage&rsquo;s responses are
        generated by automated artificial-intelligence systems, not by a human.
        Sage is for reflection and general information; it is not a substitute
        for professional medical, legal, financial, or mental-health advice.
      </P>

      <H2>Who we are</H2>
      <P>
        Sage operates the mobile app and the website at
        answerswithsage.xyz. For privacy questions, or to exercise any of the
        rights described below, contact us at{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "#e07c38" }}>
          {SUPPORT_EMAIL}
        </a>
        . For privacy purposes we are the data controller of the information
        described here.
      </P>

      <H2>Information we collect</H2>
      <P>We collect only what we need to run Sage:</P>
      <UL>
        <LI>
          <strong>Account information</strong> — your email address, an
          encrypted password (or the identifier from a third-party sign-in if
          you use one), and an optional display name, profile image, and
          birthday you choose to provide.
        </LI>
        <LI>
          <strong>Your conversations</strong> — the messages you send to Sage
          and the AI&rsquo;s replies, along with any topics, moods, or colors
          you select. We also generate and store short AI summaries of your
          conversations so Sage can keep context across sessions.
        </LI>
        <LI>
          <strong>A profile of your interests</strong> — to personalize
          responses, Sage may keep a consolidated summary of what it has
          learned about your stated interests and preferred topics.
        </LI>
        <LI>
          <strong>Usage and billing records</strong> — credit balance, credits
          consumed per feature (chat, voice), and records of in-app purchases.
          Payments are processed by Apple; we never receive or store your
          payment-card details.
        </LI>
        <LI>
          <strong>Technical data</strong> — basic device and diagnostic
          information needed to operate the service and fix crashes.
        </LI>
      </UL>
      <P>
        Sage is not directed to children. We do not knowingly collect personal
        information from anyone under 13 (or the minimum age in your region).
      </P>

      <H2>How we use your information</H2>
      <UL>
        <LI>To provide the core service — generating AI responses and voice replies to your messages.</LI>
        <LI>To maintain context and personalize Sage to your stated interests.</LI>
        <LI>To manage your account, credits, and in-app purchases.</LI>
        <LI>To keep Sage secure, prevent abuse, and debug problems.</LI>
        <LI>To comply with our legal obligations.</LI>
      </UL>
      <P>
        Our legal bases for processing (where the GDPR applies) are: performing
        our contract with you, your consent, our legitimate interests in
        operating and securing Sage, and compliance with law. We do{" "}
        <strong>not</strong> sell your personal information, and we do not use
        your conversations to serve you advertising.
      </P>

      <H2>AI providers and automated processing</H2>
      <P>
        To generate responses, your messages are processed by trusted
        third-party AI providers acting on our behalf. Depending on the feature
        you use, these include large-language-model providers (such as
        OpenRouter and OpenAI) for text, and speech providers (such as
        ElevenLabs, Deepgram, and LiveKit) for voice mode. We share only the
        content necessary to produce a response. These providers are bound by
        their own terms and act as our processors; we do not permit them to use
        your conversations to train their own models where that option is
        available to us.
      </P>
      <P>
        Sage&rsquo;s replies and any inferences it forms about your interests
        are produced by automated means. You always retain control: you can
        edit what you share, delete your conversations, and reach a human by
        emailing{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "#e07c38" }}>
          {SUPPORT_EMAIL}
        </a>
        .
      </P>

      <H2>How we share information</H2>
      <P>We share information only:</P>
      <UL>
        <LI>with the AI and infrastructure providers described above, so Sage can function;</LI>
        <LI>with Apple, which processes your in-app purchases;</LI>
        <LI>when required by law, or to protect the rights, safety, and security of users and Sage;</LI>
        <LI>in connection with a merger, acquisition, or sale of assets, in which case we will notify you.</LI>
      </UL>

      <H2>Data retention</H2>
      <P>
        We keep your account and conversation data for as long as your account
        is active. When you delete your account, we permanently delete your
        account and associated data — including your conversations, summaries,
        insights, usage records, and sessions — except where we must retain
        limited records to meet legal or accounting obligations.
      </P>

      <H2>Your choices and rights</H2>
      <P>
        You can <strong>delete your account at any time from within the app</strong>{" "}
        (Profile → Delete account), which erases your data as described above.
        Depending on where you live (including under the GDPR and the California
        CCPA/CPRA), you also have the right to:
      </P>
      <UL>
        <LI>access the personal information we hold about you;</LI>
        <LI>correct inaccurate information;</LI>
        <LI>delete your information;</LI>
        <LI>obtain a copy of your information (portability);</LI>
        <LI>object to or restrict certain processing, and withdraw consent;</LI>
        <LI>not be discriminated against for exercising these rights.</LI>
      </UL>
      <P>
        To exercise any right, email{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "#e07c38" }}>
          {SUPPORT_EMAIL}
        </a>
        . We will respond within the timeframe required by applicable law.
      </P>

      <H2>Security</H2>
      <P>
        We protect your information with industry-standard measures, including
        encryption in transit and hashed passwords. No method of transmission
        or storage is perfectly secure, but we work to safeguard your data and
        will notify you and the authorities of a breach where the law requires.
      </P>

      <H2>International transfers</H2>
      <P>
        Sage and its providers may process your information in countries other
        than your own, including the United States. Where required, we rely on
        appropriate safeguards (such as standard contractual clauses) for those
        transfers.
      </P>

      <H2>Changes to this policy</H2>
      <P>
        We may update this Privacy Policy from time to time. If we make material
        changes, we will update the effective date above and, where appropriate,
        notify you in the app.
      </P>

      <H2>Contact</H2>
      <P>
        Questions about this policy or your data? Email{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "#e07c38" }}>
          {SUPPORT_EMAIL}
        </a>
        .
      </P>
    </LegalPage>
  );
}
