import type { Metadata } from "next";
import { LegalPage, H2, P, UL, LI } from "../legal/_components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Use — Sage",
  description: "The terms that govern your use of Sage.",
};

const SUPPORT_EMAIL = "support@answerswithsage.xyz";

export default function Terms() {
  return (
    <LegalPage title="Terms of Use" effectiveDate="May 23, 2026">
      <P>
        These Terms of Use (the &ldquo;Terms&rdquo;) are an agreement between you
        and Sage (&ldquo;Sage,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;)
        governing your use of the Sage mobile app and the website at
        answerswithsage.xyz (the &ldquo;Service&rdquo;). By creating an account
        or using the Service, you agree to these Terms. If you do not agree,
        do not use the Service.
      </P>

      <H2>The Service</H2>
      <P>
        Sage is a Socratic AI companion that responds to your questions in
        conversation. <strong>Sage&rsquo;s responses are generated by automated
        artificial intelligence, not by a human.</strong> They may be
        inaccurate, incomplete, or out of date. Sage is intended for reflection
        and general information only and is{" "}
        <strong>not a substitute for professional advice</strong> — medical,
        legal, financial, mental-health, or otherwise. Do not rely on Sage for
        decisions that require a qualified professional, and in an emergency
        contact local emergency services.
      </P>

      <H2>Eligibility and your account</H2>
      <P>
        You must be at least 13 years old (or the minimum age of digital
        consent in your country) to use Sage. You are responsible for keeping
        your account credentials secure and for activity under your account.
        Provide accurate information and keep it current.
      </P>

      <H2>Acceptable use</H2>
      <P>You agree not to:</P>
      <UL>
        <LI>use Sage for any unlawful purpose or in violation of these Terms;</LI>
        <LI>attempt to disrupt, reverse-engineer, or gain unauthorized access to the Service;</LI>
        <LI>use the Service to generate or distribute harmful, abusive, infringing, or deceptive content;</LI>
        <LI>resell, scrape, or exploit the Service or its outputs without our permission.</LI>
      </UL>

      <H2>Credits, subscriptions, and payments</H2>
      <P>
        Sage uses credits to access AI features. You can buy consumable credit
        packs and subscribe to Sage Pro through in-app purchases. The following
        terms apply to purchases made on Apple platforms:
      </P>
      <UL>
        <LI>
          <strong>Billing.</strong> Purchases are processed by Apple and charged
          to your Apple Account. Subscription prices are shown in the app before
          you buy.
        </LI>
        <LI>
          <strong>Auto-renewal.</strong> A Sage Pro subscription automatically
          renews for the same period (monthly or yearly) unless you cancel at
          least 24 hours before the end of the current period. Your Apple
          Account is charged for renewal within 24 hours before the period ends.
        </LI>
        <LI>
          <strong>Managing and canceling.</strong> You can manage or cancel your
          subscription anytime in your Apple Account settings. Deleting the app
          does not cancel a subscription.
        </LI>
        <LI>
          <strong>Consumable credits.</strong> Credit packs are one-time
          purchases that add credits to your balance and are non-refundable
          once delivered, except as required by law.
        </LI>
        <LI>
          <strong>Refunds.</strong> Purchases made through Apple are subject to
          Apple&rsquo;s refund policies; we generally cannot issue refunds for
          App Store transactions directly.
        </LI>
      </UL>

      <H2>Intellectual property</H2>
      <P>
        The Service, including its software, design, and branding, belongs to
        Sage and is protected by law. We grant you a personal, non-exclusive,
        non-transferable, revocable license to use the Service for your own
        personal use. Subject to applicable law, you own the inputs you provide;
        you are responsible for ensuring you have the right to share them.
      </P>

      <H2>Disclaimers</H2>
      <P>
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as
        available&rdquo; without warranties of any kind, whether express or
        implied, including merchantability, fitness for a particular purpose,
        and non-infringement. We do not warrant that the Service will be
        uninterrupted, error-free, or that AI outputs will be accurate or
        suitable for your purposes.
      </P>

      <H2>Limitation of liability</H2>
      <P>
        To the maximum extent permitted by law, Sage will not be liable for any
        indirect, incidental, special, consequential, or punitive damages, or
        any loss of data, profits, or goodwill, arising from your use of the
        Service. Our total liability for any claim relating to the Service will
        not exceed the greater of the amount you paid us in the 12 months before
        the claim or USD $50. Some jurisdictions do not allow these limitations,
        so they may not fully apply to you.
      </P>

      <H2>Termination</H2>
      <P>
        You may stop using Sage and delete your account at any time from within
        the app (Profile → Delete account). We may suspend or terminate your
        access if you violate these Terms or to protect the Service. Provisions
        that by their nature should survive termination will survive.
      </P>

      <H2>Changes to these Terms</H2>
      <P>
        We may update these Terms from time to time. If we make material
        changes, we will update the effective date above and, where
        appropriate, notify you in the app. Continued use after changes take
        effect means you accept the updated Terms.
      </P>

      <H2>Governing law</H2>
      <P>
        These Terms are governed by the laws applicable where Sage operates,
        without regard to conflict-of-laws rules, except where local consumer
        law gives you additional protections that cannot be waived.
      </P>

      <H2>Apple-required terms</H2>
      <P>
        This agreement is between you and Sage only, not with Apple. Apple is
        not responsible for the Service or its content. Apple has no obligation
        to provide support or to address any claims relating to the Service. If
        the Service fails to conform to any applicable warranty, you may notify
        Apple for a refund of the purchase price (if any); to the maximum extent
        permitted by law, Apple has no other warranty obligation. Apple and its
        subsidiaries are third-party beneficiaries of these Terms and may
        enforce them against you.
      </P>

      <H2>Contact</H2>
      <P>
        Questions about these Terms? Email{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "#e07c38" }}>
          {SUPPORT_EMAIL}
        </a>
        .
      </P>
    </LegalPage>
  );
}
